services:
  - type: web
    name: line-bot-python
    env: python
    region: singapore # 或 oregon
    plan: free
    
    # 強制指定 Python 版本為 3.10.12 (解決編譯失敗的關鍵)
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SV5hlL1NXD9QOzbKSXF5Hzk6+AOo+dAwtEaSOHz9IBDcpSEnoEoXJ2VCUjBQHa8sX6EWknwS18mRoBGyomAIaWJQnirilGEV1t/C8zth8rTP71UajtdrXtTDh40Yk+i0N7Hw2wcZ5rS24HiJcFkBkAdB04t89/1O/w1cDnyilFU=
        sync: false
      - key: 2e9e73781d0e66c8e92fed2aa050c3bb
        sync: false

    # 建置與啟動指令
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app